iknsa_blog_comment:
    resource: "@IKNSABlogBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

iknsa_blog_post:
    resource: "@IKNSABlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

iknsa_blog_homepage:
    path:     /
    defaults: { _controller: IKNSABlogBundle:Default:index }
