<?php

namespace IKNSA\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastInserted($entity, $amount)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e FROM $entity e ORDER BY e.id DESC"
            )
            ->setMaxResults($amount)
            ->getResult();
    }
}
